const state={players:[],pitcher:null,phase:"idle",pitch:null,startedAt:0,duration:0,frame:0,windupTimer:0,hits:0,misses:0,streak:0,best:0,targetX:0,targetY:0,trail:[]};
const $=id=>document.getElementById(id);
const ui={select:$("selectScreen"),game:$("gameScreen"),stage:$("gameStage"),pitcher:$("pitcherFigure"),grid:$("pitcherGrid"),name:$("pitcherName"),season:$("seasonLabel"),ball:$("ball"),trail:$("ballTrail"),bat:$("bat"),action:$("actionButton"),status:$("status"),last:$("lastPitch"),arsenal:$("arsenal"),hits:$("hitCount"),misses:$("missCount"),best:$("bestScore"),needle:$("timingNeedle"),burst:$("contactBurst"),result:$("resultFlash")};
const setAction=label=>{ui.action.querySelector("b").textContent=label};
const movements={"4seam":[0,-4],"2seam":[-34,10],cutt:[32,3],slid:[68,22],curv:[-22,48],chan:[-38,31],fork:[7,57],splt:[6,53],sinker:[-43,34],other:[0,10]};
const MOUND_TO_PLATE_METERS=18.44;
const pitcherProfiles={
  "16108":{hand:"left",form:"over"},"13167":{hand:"right",form:"over"},"16568":{hand:"right",form:"over"},
  "14616":{hand:"left",form:"over"},"14156":{hand:"right",form:"over"},"11126":{hand:"right",form:"over"},
  "14816":{hand:"right",form:"sidearm"},"14108":{hand:"right",form:"over"},"14106":{hand:"left",form:"over"},
  "11489":{hand:"right",form:"over"},"10783":{hand:"right",form:"over"},"11411":{hand:"left",form:"over"}
};
function getPitcherProfile(player){return pitcherProfiles[String(player.player_id)]||{hand:player.throw_hand||"right",form:player.pitching_form||"over"}}
function profileLabel(profile){const hand=profile.hand==="left"?"좌완":"우완";const form=profile.form==="under"?"언더핸드":profile.form==="sidearm"?"사이드암":"오버핸드";return `${hand} ${form}`}
function clearTrail(){state.trail=[];ui.trail.classList.add("hidden");[...ui.trail.children].forEach(dot=>dot.style.opacity=0)}
function updateTrail(x,y,scale){state.trail.unshift({x,y,scale});state.trail.length=Math.min(state.trail.length,ui.trail.children.length);ui.trail.classList.remove("hidden");[...ui.trail.children].forEach((dot,index)=>{const point=state.trail[index];if(!point){dot.style.opacity=0;return}dot.style.left=`calc(50% + ${point.x}px)`;dot.style.top=`${point.y}%`;dot.style.transform=`translate(-50%,-50%) scale(${point.scale})`;dot.style.opacity=Math.max(0,.48-index*.035)})}

async function loadPlayers(){try{const response=await fetch("../output/pitchers.json",{cache:"no-store"});if(!response.ok)throw new Error(`데이터 응답 오류 (${response.status})`);const data=await response.json();state.players=data.players.filter(p=>usable(p).length);renderPitchers()}catch(error){ui.grid.innerHTML=`<div class="error">선수 데이터를 읽지 못했습니다.<br><small>${error.message}<br>run_game.ps1로 실행해 주세요.</small></div>`}}
const usable=player=>player.pitches.filter(p=>Number(p.ratio)>0&&p.pitch_type!=="기타");
function weightedAverage(pitches){const valid=pitches.filter(p=>Number(p.velocity_kmh)),total=valid.reduce((s,p)=>s+p.ratio,0)||1;return valid.reduce((s,p)=>s+p.velocity_kmh*p.ratio,0)/total}
function renderPitchers(){ui.grid.innerHTML="";state.players.forEach((player,index)=>{const pitches=usable(player),profile=getPitcherProfile(player),primary=[...pitches].sort((a,b)=>b.ratio-a.ratio)[0],card=document.createElement("button");card.className="pitcher-card";card.innerHTML=`<span class="card-number">${String(index+1).padStart(2,"0")}</span><span class="player-silhouette"></span><div class="card-content"><span class="primary-pitch">ACE · ${primary.pitch_type} ${(primary.ratio*100).toFixed(1)}%</span><h2>${player.name}</h2><div class="meta">${profileLabel(profile)} · ${pitches.length}구종 · ${weightedAverage(pitches).toFixed(1)} km/h</div></div>`;card.onclick=()=>selectPitcher(player);ui.grid.append(card)})}
function selectPitcher(player){cancelAnimationFrame(state.frame);clearTimeout(state.windupTimer);const profile=getPitcherProfile(player),lowArm=profile.form==="under"?2:profile.form==="sidearm"?1:0,hand=profile.hand==="left"?1:-1;Object.assign(state,{pitcher:player,profile,phase:"idle",hits:0,misses:0,streak:0,best:0});ui.pitcher.classList.remove("left-handed","sidearm","underhand");if(profile.hand==="left")ui.pitcher.classList.add("left-handed");if(profile.form==="sidearm")ui.pitcher.classList.add("sidearm");if(profile.form==="under")ui.pitcher.classList.add("underhand");ui.stage.style.setProperty("--release-x",`${hand*(lowArm?25:12)}px`);ui.stage.style.setProperty("--release-y",`${50.5+lowArm*2.4}%`);ui.select.classList.add("hidden");ui.game.classList.remove("hidden");ui.name.textContent=player.name;ui.season.textContent=`${player.season} SEASON · ${profileLabel(profile)}`;ui.arsenal.innerHTML=usable(player).sort((a,b)=>b.ratio-a.ratio).map(p=>`<span class="pitch-chip"><b>${p.pitch_type}</b> ${(p.ratio*100).toFixed(1)}% · ${p.velocity_kmh?p.velocity_kmh.toFixed(1):"-"}</span>`).join("");resetRound("준비되면 투구를 시작하세요");updateScore()}
function weightedPitch(){const pitches=usable(state.pitcher),total=pitches.reduce((s,p)=>s+p.ratio,0);let draw=Math.random()*total;for(const pitch of pitches){draw-=pitch.ratio;if(draw<=0)return pitch}return pitches.at(-1)}
function beginPitch(){if(state.phase!=="idle")return;state.pitch=weightedPitch();const velocity=Number(state.pitch.velocity_kmh)||135;state.duration=MOUND_TO_PLATE_METERS/(velocity/3.6)*1000;state.phase="windup";ui.result.classList.add("hidden");ui.ball.classList.add("hidden");ui.pitcher.classList.remove("windup");void ui.pitcher.offsetWidth;ui.pitcher.classList.add("windup");setAction("준비");ui.status.textContent="투수 와인드업";ui.last.textContent="릴리스 순간부터 공을 보세요";state.windupTimer=setTimeout(releasePitch,680)}
function releasePitch(){if(state.phase!=="windup")return;state.phase="pitching";state.startedAt=performance.now();clearTrail();ui.ball.classList.remove("hidden");ui.stage.classList.add("pitch-flight");setAction("스윙!");ui.status.textContent="공을 끝까지 보세요";ui.last.textContent="구종은 타격 후 공개됩니다";state.frame=requestAnimationFrame(animatePitch)}
function animatePitch(now){if(state.phase!=="pitching")return;const raw=Math.min(1,(now-state.startedAt)/state.duration),depth=raw*raw*(3-2*raw),late=Math.max(0,(raw-.32)/.68),brk=late*late*(3-2*late),profile=state.profile||getPitcherProfile(state.pitcher),hand=profile.hand==="left"?1:-1,lowArm=profile.form==="under"?2:profile.form==="sidearm"?1:0,releaseX=hand*(lowArm?25:12),releaseY=50.5+lowArm*2.4,move=movements[state.pitch.statiz_code]||movements.other,breakX=move[0]*hand*(lowArm?1.15:1),x=releaseX*(1-depth)+state.targetX*depth+breakX*brk,y=releaseY+(12.5+state.targetY-(releaseY-50.5))*depth-2.1*Math.sin(Math.PI*raw)+move[1]*brk*.065,scale=.38+Math.pow(raw,2.15)*3.05;ui.ball.style.left=`calc(50% + ${x}px)`;ui.ball.style.top=`${y}%`;ui.ball.style.transform=`scale(${scale}) rotate(${hand*raw*1080}deg)`;ui.ball.style.filter=`blur(${raw>.94?(raw-.94)*5:0}px)`;updateTrail(x,y,Math.max(.28,scale*.72));ui.needle.style.left=`${Math.min(99,raw*100)}%`;if(raw>=1)resolveMiss("루킹");else state.frame=requestAnimationFrame(animatePitch)}
function swing(){if(state.phase!=="pitching")return;const progress=Math.min(1,(performance.now()-state.startedAt)/state.duration);state.phase="resolved";cancelAnimationFrame(state.frame);ui.bat.classList.add("swinging");setTimeout(()=>ui.bat.classList.remove("swinging"),260);const error=Math.abs(progress-.91);if(error<=.045)resolveHit("PERFECT!","result-perfect",3);else if(error<=.105)resolveHit(progress<.91?"조금 빨랐지만 안타!":"조금 늦었지만 안타!","result-hit",1);else resolveMiss(progress<.91?"너무 빨랐습니다":"너무 늦었습니다")}
function resolveHit(message,className,points){state.hits++;state.streak+=points;state.best=Math.max(state.best,state.streak);showResult(message,className);ui.burst.classList.remove("hidden");ui.burst.style.animation="none";void ui.burst.offsetWidth;ui.burst.style.animation="";ui.stage.classList.remove("camera-hit");void ui.stage.offsetWidth;ui.stage.classList.add("camera-hit");setTimeout(()=>{ui.burst.classList.add("hidden");ui.stage.classList.remove("camera-hit")},500)}
function resolveMiss(message){if(state.phase==="pitching"){state.phase="resolved";cancelAnimationFrame(state.frame)}state.misses++;state.streak=0;showResult(message,"result-miss")}
function showResult(message,className){ui.stage.classList.remove("pitch-flight");ui.status.className=`status ${className}`;ui.status.textContent=message;const detail=`${state.pitch.pitch_type} · ${state.pitch.velocity_kmh?state.pitch.velocity_kmh.toFixed(1):"-"} km/h · 구사율 ${(state.pitch.ratio*100).toFixed(1)}%`;ui.last.textContent=detail;ui.result.className=`result-flash ${className}`;ui.result.querySelector("strong").textContent=message;ui.result.querySelector("span").textContent=detail;setAction("다음 투구");ui.ball.classList.add("hidden");updateScore();setTimeout(()=>{if(state.phase==="resolved")state.phase="idle"},180)}
function resetRound(message="다음 공을 준비하세요"){clearTimeout(state.windupTimer);state.phase="idle";state.targetX=(Math.random()-.5)*70;state.targetY=(Math.random()-.5)*5.5;ui.pitcher.classList.remove("windup");ui.stage.classList.remove("pitch-flight","camera-hit");ui.result.classList.add("hidden");ui.ball.classList.add("hidden");clearTrail();ui.ball.style.transform="";ui.ball.style.filter="";ui.needle.style.left="0%";ui.status.className="status";ui.status.textContent=message;ui.last.textContent="SPACE 또는 버튼을 누르세요";setAction("투구 시작")}
function updateScore(){ui.hits.textContent=state.hits;ui.misses.textContent=state.misses;ui.best.textContent=state.best}
function handleAction(){if(state.phase==="idle"){state.targetX=(Math.random()-.5)*70;state.targetY=(Math.random()-.5)*5.5;beginPitch()}else if(state.phase==="pitching")swing();else if(state.phase==="resolved")resetRound()}
ui.action.onclick=handleAction;$("backButton").onclick=()=>{cancelAnimationFrame(state.frame);clearTimeout(state.windupTimer);ui.game.classList.add("hidden");ui.select.classList.remove("hidden")};window.addEventListener("keydown",event=>{if(event.code==="Space"&&!ui.game.classList.contains("hidden")){event.preventDefault();handleAction()}});loadPlayers();
