const state={players:[],pitcher:null,phase:"idle",pitch:null,startedAt:0,duration:0,frame:0,hits:0,misses:0,streak:0,best:0,targetX:0};
const $=id=>document.getElementById(id);
const ui={select:$("selectScreen"),game:$("gameScreen"),grid:$("pitcherGrid"),name:$("pitcherName"),season:$("seasonLabel"),ball:$("ball"),bat:$("bat"),action:$("actionButton"),status:$("status"),last:$("lastPitch"),arsenal:$("arsenal"),hits:$("hitCount"),misses:$("missCount"),best:$("bestScore"),needle:$("timingNeedle"),burst:$("contactBurst")};
const movements={"4seam":[0,-3],"2seam":[-18,8],cutt:[17,2],slid:[34,16],curv:[-12,34],chan:[-20,23],fork:[4,40],splt:[3,38],sinker:[-23,24],other:[0,8]};

async function loadPlayers(){try{const response=await fetch("../output/pitchers.json",{cache:"no-store"});if(!response.ok)throw new Error(`데이터 응답 오류 (${response.status})`);const data=await response.json();state.players=data.players.filter(p=>usable(p).length);renderPitchers()}catch(error){ui.grid.innerHTML=`<div class="error">선수 데이터를 읽지 못했습니다.<br><small>${error.message}<br>run_game.ps1로 실행해 주세요.</small></div>`}}
const usable=player=>player.pitches.filter(p=>Number(p.ratio)>0&&p.pitch_type!=="기타");
function weightedAverage(pitches){const valid=pitches.filter(p=>Number(p.velocity_kmh)),total=valid.reduce((s,p)=>s+p.ratio,0)||1;return valid.reduce((s,p)=>s+p.velocity_kmh*p.ratio,0)/total}
function renderPitchers(){ui.grid.innerHTML="";state.players.forEach((player,index)=>{const pitches=usable(player),primary=[...pitches].sort((a,b)=>b.ratio-a.ratio)[0],card=document.createElement("button");card.className="pitcher-card";card.dataset.number=String(index+1).padStart(2,"0");card.innerHTML=`<span class="primary-pitch">${primary.pitch_type} ${(primary.ratio*100).toFixed(1)}%</span><h2>${player.name}</h2><div class="meta">${player.season} · ${pitches.length}구종 · 평균 ${weightedAverage(pitches).toFixed(1)} km/h</div>`;card.onclick=()=>selectPitcher(player);ui.grid.append(card)})}
function selectPitcher(player){cancelAnimationFrame(state.frame);Object.assign(state,{pitcher:player,phase:"idle",hits:0,misses:0,streak:0,best:0});ui.select.classList.add("hidden");ui.game.classList.remove("hidden");ui.name.textContent=player.name;ui.season.textContent=`${player.season} SEASON · 실제 구사율 적용`;ui.arsenal.innerHTML=usable(player).sort((a,b)=>b.ratio-a.ratio).map(p=>`<span class="pitch-chip"><b>${p.pitch_type}</b> ${(p.ratio*100).toFixed(1)}% · ${p.velocity_kmh?p.velocity_kmh.toFixed(1):"-"}</span>`).join("");resetRound("준비되면 투구를 시작하세요");updateScore()}
function weightedPitch(){const pitches=usable(state.pitcher),total=pitches.reduce((s,p)=>s+p.ratio,0);let draw=Math.random()*total;for(const pitch of pitches){draw-=pitch.ratio;if(draw<=0)return pitch}return pitches.at(-1)}
function beginPitch(){if(state.phase!=="idle")return;state.pitch=weightedPitch();const velocity=Number(state.pitch.velocity_kmh)||135;state.duration=Math.max(560,Math.min(840,(145/velocity)*650));state.startedAt=performance.now();state.phase="pitching";ui.ball.classList.remove("hidden");ui.action.textContent="스윙!";ui.status.textContent="공을 끝까지 보세요";ui.last.textContent="구종은 타격 후 공개됩니다";state.frame=requestAnimationFrame(animatePitch)}
function animatePitch(now){if(state.phase!=="pitching")return;const raw=Math.min(1,(now-state.startedAt)/state.duration),eased=raw*raw*(3-2*raw),move=movements[state.pitch.statiz_code]||movements.other,x=state.targetX*eased+move[0]*Math.sin(Math.PI*eased)*eased,y=27+44*eased+move[1]*eased*eased*.12,scale=.75+eased*1.25;ui.ball.style.left=`calc(50% + ${x}px)`;ui.ball.style.top=`${y}%`;ui.ball.style.transform=`scale(${scale})`;ui.needle.style.left=`${Math.min(99,raw*100)}%`;if(raw>=1)resolveMiss("루킹") ;else state.frame=requestAnimationFrame(animatePitch)}
function swing(){if(state.phase!=="pitching")return;const progress=Math.min(1,(performance.now()-state.startedAt)/state.duration);state.phase="resolved";cancelAnimationFrame(state.frame);ui.bat.classList.add("swinging");setTimeout(()=>ui.bat.classList.remove("swinging"),260);const error=Math.abs(progress-.91);if(error<=.045)resolveHit("PERFECT!","result-perfect",3);else if(error<=.105)resolveHit(progress<.91?"조금 빨랐지만 안타!":"조금 늦었지만 안타!","result-hit",1);else resolveMiss(progress<.91?"너무 빨랐습니다":"너무 늦었습니다")}
function resolveHit(message,className,points){state.hits++;state.streak+=points;state.best=Math.max(state.best,state.streak);showResult(message,className);ui.burst.classList.remove("hidden");ui.burst.style.animation="none";void ui.burst.offsetWidth;ui.burst.style.animation="";setTimeout(()=>ui.burst.classList.add("hidden"),500)}
function resolveMiss(message){if(state.phase==="pitching"){state.phase="resolved";cancelAnimationFrame(state.frame)}state.misses++;state.streak=0;showResult(message,"result-miss")}
function showResult(message,className){ui.status.className=`status ${className}`;ui.status.textContent=message;ui.last.textContent=`${state.pitch.pitch_type} · ${state.pitch.velocity_kmh?state.pitch.velocity_kmh.toFixed(1):"-"} km/h · 구사율 ${(state.pitch.ratio*100).toFixed(1)}%`;ui.action.textContent="다음 투구";ui.ball.classList.add("hidden");updateScore();setTimeout(()=>{if(state.phase==="resolved")state.phase="idle"},180)}
function resetRound(message="다음 공을 준비하세요"){state.phase="idle";state.targetX=(Math.random()-.5)*58;ui.ball.classList.add("hidden");ui.ball.style.transform="";ui.needle.style.left="0%";ui.status.className="status";ui.status.textContent=message;ui.last.textContent="SPACE 또는 아래 버튼";ui.action.textContent="투구 시작"}
function updateScore(){ui.hits.textContent=state.hits;ui.misses.textContent=state.misses;ui.best.textContent=state.best}
function handleAction(){if(state.phase==="idle"){state.targetX=(Math.random()-.5)*58;beginPitch()}else if(state.phase==="pitching")swing();else if(state.phase==="resolved")resetRound()}
ui.action.onclick=handleAction;$("backButton").onclick=()=>{cancelAnimationFrame(state.frame);ui.game.classList.add("hidden");ui.select.classList.remove("hidden")};window.addEventListener("keydown",event=>{if(event.code==="Space"&&!ui.game.classList.contains("hidden")){event.preventDefault();handleAction()}});loadPlayers();
